# Generated by Django 5.2.7 on 2025-11-10 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_experience_experiencehighlight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('emoji', models.CharField(default='💻', help_text='Emoji for the project image', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='project_images/')),
                ('summary', models.TextField()),
                ('order', models.IntegerField(default=0, help_text='Display order (higher = shows first)')),
            ],
            options={
                'verbose_name_plural': 'Projects',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProjectPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='resume.project')),
            ],
            options={
                'verbose_name_plural': 'Project Points',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon_url', models.URLField(help_text='DevIcon URL from https://devicon.dev')),
                ('order', models.IntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technologies', to='resume.project')),
            ],
            options={
                'verbose_name_plural': 'Technologies',
                'ordering': ['order'],
            },
        ),
    ]
