# Generated by Django 5.2.7 on 2025-11-11 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_project_projectpoint_technology'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Home',
        ),
    ]
