# Generated by Django 5.2.7 on 2025-11-11 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_delete_home'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(help_text="Short display name (e.g., 'CCNA', 'AWS')", max_length=50)),
                ('image_url', models.URLField(help_text='URL to certification badge image')),
                ('order', models.IntegerField(default=0, help_text='Display order')),
            ],
            options={
                'verbose_name_plural': 'Certifications',
                'ordering': ['order'],
            },
        ),
    ]
