# Generated by Django 5.2.7 on 2025-11-12 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_certification'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Section title (e.g., 'Interests', 'Hobbies')", max_length=200)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
            ],
            options={
                'verbose_name_plural': 'Carousel Sections',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CarouselItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(help_text='Background image for the card', upload_to='carousel_images/')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=False, help_text='First item in each section should be active')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='resume.carouselsection')),
            ],
            options={
                'verbose_name_plural': 'Carousel Items',
                'ordering': ['order'],
            },
        ),
    ]
