# Generated by Django 5.2.7 on 2025-11-12 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_carouselsection_carouselitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carouselitem',
            name='is_active',
        ),
    ]
